In [2]:
import numpy as np

In [5]:
np.__version__

'1.24.3'

In [6]:
np.zeros?

In [7]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [11]:
arr=np.arange(0,100)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [15]:
np.arange(-100,0)

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1])

In [16]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [17]:
np.arange(0,9,(3,3))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [18]:
np.arange(0,10,(3,3))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [19]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
np.array(0,1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [21]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [1]:
import numpy as np


In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
l=[1,2,3,4,5]

In [4]:
l

[1, 2, 3, 4, 5]

In [5]:
#difference b/w list & array:
#in list many types of datatypes can be stored and in array same type of data is stored
#list has heterheterogeneous data & array has homoghomogenous data

In [6]:
l2=[x for x in range(0,10)] #list comprehension

In [7]:
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
l3=[str(x) for x in l2] #elements from l2 converted into string

In [9]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
l4=[x*x for x in l2]

In [11]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [12]:
type(l4)

list

In [13]:
import array   #import array module

In [14]:
array?

In [15]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array
    
    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |  
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |  
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined

In [16]:
arr=array.array('i',12)

TypeError: 'int' object is not iterable

In [17]:
arr=array.array('i',l2) #convert to array using array module

In [18]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
type(arr)

array.array

In [20]:
arr1=array.array('i',x*x for x in l2)

SyntaxError: Generator expression must be parenthesized (1329281317.py, line 1)

In [22]:
arr1=array.array('i',[x*x for x in l2])

In [23]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [24]:
import numpy as np

In [25]:
np.array(l2)  #convert to array using numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
np.array([x-3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [28]:
np.array([x+3 for x in l2])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [30]:
np.array([1,2,3,4,5],dtype='str')

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [31]:
np.array([1,2,3,4,5],dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [32]:
l5=[[1,2,3],[4,5,5]]

In [33]:
l5

[[1, 2, 3], [4, 5, 5]]

In [39]:
l6=[range(i,i+3) for i in range[0,6]]

In [40]:
l6

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7), range(5, 8)]

In [41]:
np.array(l6)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [43]:
l7=[range(i,i+4) for i in [4,4]]

In [44]:
l7

[range(4, 8), range(4, 8)]

In [45]:
np.array(l7)

array([[4, 5, 6, 7],
       [4, 5, 6, 7]])

In [47]:
l8=[range(i,i+3) for i in [1,2,3]]

In [48]:
l8

[range(1, 4), range(2, 5), range(3, 6)]

In [49]:
np.array(l8)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [50]:
np.zeros(10)  #all default value 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [53]:
np.zeros([3,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
np.ones((2,2))  #all default value 1

array([[1., 1.],
       [1., 1.]])

In [57]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [58]:
arr0=np.zeros([3,4])

In [59]:
arr0[1:2,1:2]=1

In [60]:
arr0

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
arr3=np.zeros([10,10])

In [67]:
arr3[1:9,1:9]=1  #replace elements using indexing

In [68]:
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
arr3[1:9,1:9]=9

In [70]:
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
arr3[2:8,2:8]=8

In [76]:
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 8., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 7., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 7., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 7., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 7., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 7., 0.],
       [0., 9., 8., 7., 7., 7., 7., 7., 7., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
arr3[3:7,3:7]=7

In [78]:
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 8., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 7., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 7., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 7., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 7., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 7., 0.],
       [0., 9., 8., 7., 7., 7., 7., 7., 7., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
arr3[4:6,4:6]=6

In [80]:
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 9., 9., 9., 9., 9., 9., 9., 9., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 8., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 7., 0.],
       [0., 9., 8., 7., 6., 6., 7., 8., 7., 0.],
       [0., 9., 8., 7., 6., 6., 7., 8., 7., 0.],
       [0., 9., 8., 7., 7., 7., 7., 8., 7., 0.],
       [0., 9., 8., 8., 8., 8., 8., 8., 7., 0.],
       [0., 9., 8., 7., 7., 7., 7., 7., 7., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
np.full((3,4),3.14)  #'full' for all elements are same where we assign size and value

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [89]:
np.eye(3,3)  #'eye' for identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.transpose(np.eye(3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
import numpy as np


In [2]:
a1=np.ones((6,6))

In [3]:
a1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [4]:
np.full((6,6),64)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [5]:
#linspace - linearly spaced elements 
# to divide a given range in equal mentioned parts

In [9]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [14]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [15]:
np.random?   #import random module with np.random & add next function with '.'

In [17]:
np.random.random((3,3))   # values b/w 0 to 1 

array([[0.22435541, 0.85086588, 0.57100549],
       [0.26492002, 0.62983677, 0.30070405],
       [0.80649259, 0.28340579, 0.52527107]])

In [18]:
np.random.random(3)

array([0.86451958, 0.71975134, 0.10433155])

In [19]:
np.random.normal?

In [20]:
np.random.normal(0,1,10) # values with mean 0 & standard deviation 1

array([-0.20182646, -1.89907088,  1.5763608 , -1.84430947,  0.59707123,
        0.39986407,  1.60352376,  1.02736873,  1.46107115,  0.1014651 ])

In [22]:
np.random.normal(0,1,(2,2))  #can have +ve/-ve elements

array([[ 0.47461351,  0.46168982],
       [-0.17448898, -2.07610943]])

In [25]:
np.random.seed(100)      #seed to fix the random values
np.random.random(10)     

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [26]:
np.random.seed(10)
np.random.normal(0,1,(2,2))

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385]])

In [27]:
np.random.randint(50,100,36)  #only positive integers 

array([99, 58, 59, 50, 92, 90, 86, 66, 86, 97, 61, 74, 93, 83, 58, 86, 64,
       99, 63, 55, 63, 75, 63, 78, 72, 80, 80, 75, 62, 51, 81, 86, 77, 68,
       79, 63])

In [28]:
np.random.randn?    #returns values from standard normal distribution with mean and variance

In [29]:
#operations on arrays:

In [34]:
ary=np.random.randint(0,100,(2,2))

In [35]:
ary

array([[84, 96],
       [88, 44]])

In [36]:
ary.ndim  #to find dimensions of array

2

In [37]:
ary.size   #no of elements in array

4

In [38]:
ary.shape  #finds proper size of array 

(2, 2)

In [39]:
ary.dtype  #datatype of array

dtype('int32')

In [40]:
#array indexing

In [44]:
ar1=np.random.randint(0,45,10)

In [45]:
ar1

array([11, 12, 28, 32, 15, 44, 40, 42, 43, 33])

In [46]:
ar1[0]

11

In [48]:
ar1[4]

15

In [49]:
ar1[-1]

33

In [50]:
ar1[:5]  #range of indexing before 5th position

array([11, 12, 28, 32, 15])

In [52]:
ar1[4:]   #range of indexing after 4th position

array([15, 44, 40, 42, 43, 33])

In [53]:
ar1[4:7]

array([15, 44, 40])

In [55]:
ar1[6]=56   #replace element at given position

In [56]:
ar1

array([11, 12, 28, 32, 15, 44, 56, 42, 43, 33])

In [1]:
import numpy as np

In [2]:
A1=np.arange(0,9).reshape(3,3)

In [3]:
A1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
As=A1[1:3,1:3]   #sub-array from an array

In [5]:
As

array([[4, 5],
       [7, 8]])

In [ ]:
#Shallow copying: the view is changed here but the main array is not changed.
#''.copy' is used to change from main file

In [8]:
As[1,1]=20      #changing an element of sub-array

In [9]:
As

array([[ 4,  5],
       [ 7, 20]])

In [10]:
A1            #Main array is also modified

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 20]])

In [11]:
#Deep copying

In [14]:
As1=A1[:2,:2].copy()

In [15]:
As1

array([[0, 1],
       [3, 4]])

In [22]:
As1[0,0]=11

In [24]:
As1     #main is not modified 

array([[11,  1],
       [ 3,  4]])

In [28]:
import array

In [29]:
b1=np.array([1,2,3])

In [30]:
b1

array([1, 2, 3])

In [31]:
b1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [32]:
b2=np.array([1,2,3,4])

In [34]:
b3=b2.reshape(2,2)  #reshape to change dimensions of array

In [35]:
b3

array([[1, 2],
       [3, 4]])

In [38]:
b4=b3.reshape(1,4)

In [39]:
b4

array([[1, 2, 3, 4]])

In [41]:
b3.ravel()     #flattens the array(method 1) 1D from 2D/3D array

array([1, 2, 3, 4])

In [42]:
b3.flatten()   #flattens the array(method 2) 1D from 2D/3D array

array([1, 2, 3, 4])

In [46]:
b3.flatten?

In [47]:
b3.ravel?

In [50]:
b4=b3.flatten()

In [51]:
b4

array([1, 2, 3, 4])

In [52]:
b4[:,np.newaxis]  #coverts 1D array to 2D

array([[1],
       [2],
       [3],
       [4]])

In [53]:
#Concatenation/Joining of two arrays
#axis_____ 0=row, 1=column {Axis is used to specify row and column}
#only for same types of arrays(1D,2D,3D)
#axis is used for columns

In [54]:
np.concatenate?

In [55]:
As1

array([[11,  1],
       [ 3,  4]])

In [56]:
b3

array([[1, 2],
       [3, 4]])

In [57]:
np.concatenate([As1,b3])    #added in rows  (no. of columns should be equal)

array([[11,  1],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4]])

In [58]:
np.concatenate([As1,b3],axis=1)   #added in columns   (no. of rows should be equal)

array([[11,  1,  1,  2],
       [ 3,  4,  3,  4]])

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],
             [6,5,4]])

In [4]:
#stack arrays in sequence row wise
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [5]:
#stack arrays in sequence column wise
y=np.array([[10,11],
           [12,13]])

In [6]:
np.hstack((grid,y))

array([[ 9,  8,  7, 10, 11],
       [ 6,  5,  4, 12, 13]])

In [12]:
x1=np.array([9,9,9])

In [13]:
x1[:,np.newaxis]

array([[9],
       [9],
       [9]])

In [15]:
np.hstack((grid,x1))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [16]:
y[:,np.newaxis]

array([[[10, 11]],

       [[12, 13]]])

In [17]:
#np.Split to divide array

In [18]:
np.split?  #spilt array as views with given indices

In [19]:
np.vsplit?  #spilt array row wise

In [21]:
np.hsplit?   #spilt array column wise

In [23]:
x2=np.array([1,2,3,4,5])

In [25]:
np.split(x2,5)   #single splits

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [26]:
np.split(x2,[2,3])   #one before2, b/w 2-3, after 3

[array([1, 2]), array([3]), array([4, 5])]

In [28]:
np.split(x2,[1,4])

[array([1]), array([2, 3, 4]), array([5])]

In [29]:
np.split(x2,[1,2,4])

[array([1]), array([2]), array([3, 4]), array([5])]

In [30]:
np.split(x2,[1,3,4])

[array([1]), array([2, 3]), array([4]), array([5])]

In [31]:
x3=np.arange(0,8).reshape(2,4)

In [32]:
x3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
np.vsplit(x3,2)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]

In [34]:
np.hsplit(x3,2)

[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]

In [36]:
np.hsplit(x3,[2,3])

[array([[0, 1],
        [4, 5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]])]

In [38]:
x4=np.arange(0,16).reshape(4,4)

In [39]:
x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.vsplit(x4,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [41]:
np.abs(-543)

543

In [42]:
np.min(x4,axis=0)

array([0, 1, 2, 3])

In [43]:
np.max(x4,axis=1)

array([ 3,  7, 11, 15])

In [44]:
np.argmin(x4)   #index of min

0

In [45]:
np.argmax(x4)    #index of max

15

In [46]:
x1

array([9, 9, 9])

In [47]:
np.sum(x1)

27

In [48]:
np.sum(x4,axis=0)

array([24, 28, 32, 36])

In [50]:
np.sum(x4,axis=1)

array([ 6, 22, 38, 54])

In [51]:
x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.prod(x4)

0

In [53]:
x2

array([1, 2, 3, 4, 5])

In [54]:
np.prod(x2)   #factorial

120

In [55]:
np.median(x2)   #median

3.0

In [57]:
np.percentile?   #percentile

In [58]:
np.percentile(x2,25)

2.0

In [1]:
np.sort?

Object `np.sort` not found.


In [19]:
C1[::2,::2]=0
C1[1::2,1::2]=0

In [20]:
C1

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])