In [ ]:
#ASSIGNMENT 2

In [1]:
import numpy as np

In [3]:
#1. Create 1-D, 2-D and 3-D numpy array
arr=np.random.random(6)

In [4]:
arr

array([0.72394562, 0.33521207, 0.97919878, 0.51826455, 0.8807387 ,
       0.09243865])

In [5]:
arr1=np.random.random((2,2))

In [6]:
arr1

array([[0.18827406, 0.57199542],
       [0.32621984, 0.738229  ]])

In [13]:
arr3=np.random.random((2,2,2))

In [10]:
arr3

array([[[0.8356056 , 0.30067936],
        [0.03859786, 0.81462144]],

       [[0.35843947, 0.01696967],
        [0.96322856, 0.4017142 ]]])

In [15]:
#2. Print data type of array. 
arr1.dtype

dtype('float64')

In [16]:
#3. Print shape and dimensions of all the three different array.
arr.shape

(6,)

In [17]:
arr1.shape

(2, 2)

In [18]:
arr3.shape

(2, 2, 2)

In [19]:
arr.ndim

1

In [20]:
arr1.ndim

2

In [21]:
arr3.ndim

3

In [22]:
#4. Create another 1-D array of 12 elements filled with zero 
ar=np.zeros(12)

In [23]:
ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
#5. Create another 2-D array elements filled with ones.
ar1=np.ones((2,2))

In [25]:
ar1

array([[1., 1.],
       [1., 1.]])

In [26]:
#6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.
maths=np.random.randint(0,100,20)

In [27]:
maths

array([46, 53, 20, 84, 24, 84, 45, 31, 23, 90, 12, 56, 37, 26, 53, 73, 82,
       28, 38, 64])

In [81]:
#7. Sort the above array in ascending and descending order. 
maths=np.random.randint(0,100,20)
maths

array([52, 98, 53, 66, 98, 14, 34, 24, 15, 60, 58, 16,  9, 93, 86,  2, 27,
        4, 31,  1])

In [85]:
C1=np.sort(maths)

In [87]:
C1

array([ 1,  2,  4,  9, 14, 15, 16, 24, 27, 31, 34, 52, 53, 58, 60, 66, 86,
       93, 98, 98])

In [84]:
np.sort(maths)[::-1]

array([98, 98, 93, 86, 66, 60, 58, 53, 52, 34, 31, 27, 24, 16, 15, 14,  9,
        4,  2,  1])

In [88]:
#8. Create a copy of sorted array to another variable by deep copying.
c1=C1[::].copy()

In [89]:
c1

array([ 1,  2,  4,  9, 14, 15, 16, 24, 27, 31, 34, 52, 53, 58, 60, 66, 86,
       93, 98, 98])

In [2]:
import numpy as np

In [4]:
#9. Create 2-D array of 5x5 which is an identity matrix and then convert 1D.
B5=np.eye(5,5)

In [5]:
B5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
B5.reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [8]:
#10. Create 2-D array of 3x3. Add one more row to it. 
B1=np.arange(0,9).reshape(3,3)

In [9]:
B1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
b1=np.array([9,10,11]).reshape(1,3)

In [15]:
b1

array([[ 9, 10, 11]])

In [18]:
b3=np.concatenate([B1,b1])

In [19]:
b3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
#11. Split above array created vertically and horizontally.
np.vsplit(b3,2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [27]:
np.hsplit(b3,3)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [28]:
#12. Create 4x4 identity matrix. Add 4 to each element. 
matrix=np.eye(4,4)

In [29]:
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
mat=matrix+4

In [31]:
mat

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [32]:
#13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and round (with 2 decimal’s). 
ary=np.array([2.6457,6.8889,9.2341,7.1123,5.0543])

In [33]:
ary

array([2.6457, 6.8889, 9.2341, 7.1123, 5.0543])

In [34]:
np.ceil(ary)

array([ 3.,  7., 10.,  8.,  6.])

In [35]:
np.floor(ary)

array([2., 6., 9., 7., 5.])

In [36]:
np.round(ary,2)

array([2.65, 6.89, 9.23, 7.11, 5.05])

In [37]:
#14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.
B3=ary=np.random.randint(0,25,(5,5))

In [38]:
B3

array([[ 9, 22, 24, 18, 15],
       [20, 21, 21,  4,  1],
       [ 6, 20,  7, 14,  8],
       [17, 18, 12, 24, 15],
       [ 4,  2, 22,  8,  3]])

In [39]:
np.min(B3,axis=1)

array([ 9,  1,  6, 12,  2])

In [40]:
np.max(B3,axis=1)

array([24, 21, 20, 24, 22])

In [41]:
np.var(B3,axis=1)

array([28.24, 80.24, 28.  , 15.76, 54.56])

In [42]:
np.std(B3,axis=1)

array([5.3141321 , 8.95767827, 5.29150262, 3.96988665, 7.38647413])

In [43]:
#15. Create a null vector of size 10 with 6th value filled with 200.
B4=np.full((10),np.nan)
B4

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [44]:
B4[6]=200

In [45]:
B4

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [46]:
#16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.
B5=np.arange(100,151)

In [47]:
B5

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [48]:
#17. Reverse the above vector
B5[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [39]:
#18. Create a 5x5 matrix with values ranging from 0-24 using some function.
ar3=np.arange(0,25).reshape(5,5)

In [40]:
ar3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
#19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8]
B10=np.array([1,0,2,0,0,4,0,8])

In [50]:
B10

array([1, 0, 2, 0, 0, 4, 0, 8])

In [51]:
np.nonzero(B10)

(array([0, 2, 5, 7], dtype=int64),)

In [8]:
#20 Create a 10x10 matrix with 1 on the borders and 0 inside.
ar4=np.ones([10,10])

In [9]:
ar4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
ar4[1:9,1:9]=0

In [11]:
ar4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
#21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern. 
B7=np.ones([8,8])
B7[::2,::2]=0
B7[1::2,1::2]=0

In [53]:
B7

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [3]:
import numpy as np

In [10]:
#22. Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction
X1=np.random.seed(100)
X1=np.random.randint(0,50,[3,3])

In [11]:
X1

array([[ 8, 24,  3],
       [39, 23, 15],
       [48, 10, 30]])

In [12]:
X2=np.random.seed(100)
X2=np.random.randint(50,100,[3,3])

In [13]:
X2

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80]])

In [14]:
X1+X2

array([[ 66,  98,  56],
       [128,  96,  80],
       [146,  70, 110]])

In [15]:
X1-X2

array([[-50, -50, -50],
       [-50, -50, -50],
       [-50, -50, -50]])

In [16]:
X1*X2

array([[ 464, 1776,  159],
       [3471, 1679,  975],
       [4704,  600, 2400]])

In [ ]:
#ASSIGNMENT 1:

In [91]:
#1. Import Numpy as np 
import numpy as np

In [93]:
#2.Create an array of 10 zeros  
D1=np.zeros(10)

In [94]:
D1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
#3.Create an array of 10 ones  
D2=np.ones(10)

In [96]:
D2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
#4.Create an array of the integers from 10 to 50 
D3=np.arange(10,51)

In [98]:
D3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [99]:
#5.Create an array of all the even integers from 10 to 50 
D4=np.arange(10,51,2)

In [100]:
D4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [101]:
#6.Create a 3x3 matrix with values ranging from 0 to 8
D5=np.arange(0,9).reshape(3,3)

In [102]:
D5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
#7. Create a 3x3 identity matrix 
D6=np.eye(3,3)

In [104]:
D6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
#8. use NumPy to generate a random number between 0 to 1
np.random.random(1)

array([0.07898787])

In [107]:
#9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution  
D7=2.5*np.random.randn(25)+3  

In [108]:
D7

array([ 5.52766536, -0.60192796,  5.45142286,  6.44249078,  2.42428729,
        4.20231029, -0.16727645,  3.67751273,  8.35190806,  4.1884226 ,
        3.61631222,  0.28956511, -2.95395649,  1.90912801, -2.18102965,
       -0.2385996 ,  1.83994104,  2.85743341,  3.68982434,  6.73628805,
        4.41705159, -2.75843565,  6.4425018 ,  0.03153295,  3.19848263])

In [109]:
#10. Create a matrix of 10x10 matrix of linearly spaced elements from 0.01 to 1
D8=np.linspace(0.01,1,100).reshape(10,10)

In [110]:
D8

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [111]:
#11. Create an array of 20 linearly spaced points between 0 and 1 
D9=np.linspace(0,1,20)

In [112]:
D9

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [114]:
#12.Create a 5x5 matrix as  
#array([[ 1,  2,  3,  4,  5], 
 #      [ 6,  7,  8,  9, 10], 
  #     [11, 12, 13, 14, 15], 
   #    [16, 17, 18, 19, 20], 
    #   [21, 22, 23, 24, 25]]) 

In [115]:
D10=np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25]])

In [116]:
D10

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
# a.       array([[12, 13, 14, 15], 
#             [17, 18, 19, 20], 
#                      [22, 23, 24, 25]])

In [120]:
D10[2::,1::]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [124]:
# b. 20
D10[3,4]

20

In [17]:
import numpy as np

In [18]:
# c.y([[ 2], 
#    [ 7], 
#    [12]]) 

In [21]:
D10[:3,1]

array([ 2,  7, 12])

In [22]:
#d.array([21, 22, 23, 24, 25])

In [23]:
D10[4,::]

array([21, 22, 23, 24, 25])

In [24]:
#e.array([[16, 17, 18, 19, 20], 
#        [21, 22, 23, 24, 25]])  

In [25]:
D10[3::,::]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
#13. Get sum of all values in matrix

In [29]:
X3=np.random.seed(100)
X3=np.random.randint(0,100,[5,5])

In [30]:
X3

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34],
       [24, 15, 60, 58, 16],
       [ 9, 93, 86,  2, 27]])

In [31]:
np.sum(X3)

1222

In [32]:
#14. Get sum of all the columns in matrix 

In [33]:
np.sum(X3,axis=1)

array([265, 302, 265, 173, 217])

In [34]:
#15. Get Standard deviation , varience , minimum, maximum from matrix row wise.

In [35]:
np.std(X3,axis=0)

array([18.97998946, 32.4135774 , 14.96662955, 30.86486676, 31.88353807])

In [36]:
np.var(X3,axis=0)

array([ 360.24, 1050.64,  224.  ,  952.64, 1016.56])

In [37]:
np.min(X3,axis=0)

array([ 8, 10, 60,  2, 16])

In [38]:
np.max(X3,axis=0)

array([53, 93, 98, 87, 98])

In [39]:
#16. create 2 d matrix with all border values nan and 1 in middle

In [42]:
X4=np.full((4,4),np.nan)

In [48]:
X4[1:3,1:3]=1

In [49]:
X4

array([[nan, nan, nan, nan],
       [nan,  1.,  1., nan],
       [nan,  1.,  1., nan],
       [nan, nan, nan, nan]])